### ISSUE TITLE
Quick Start - git fails

### ISSUE THREAD

**Issue by jlpoolen** [LinkedInAttic/cleo#1]
Quick Start Guide has:

   You can follow the steps below to set up a typeahead service for public companies listed at Nasdaq.

```
   Download cleo-primer from Github.

     git clone --depth 1 git@github.com:jingwei/cleo-primer.git cleo-primer
```

When I copy pasted the command line, I was denied access:

jlpoole@themis /usr/local/src $ git clone --depth 1 git@github.com:jingwei/cleo-primer.git cleo-primer
Cloning into cleo-primer...
The authenticity of host 'github.com (207.97.227.239)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,207.97.227.239' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
jlpoole@themis /usr/local/src $ git clone --depth 1 git@github.com:jingwei/cleo-primer.git cleo-primer
Cloning into cleo-primer...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
jlpoole@themis /usr/local/src $

**Comment by dbasch** [comment]
I assume you're looking here: http://sna-projects.com/cleo/quickstart.php

It should say:

git clone --depth 1 https://github.com/jingwei/cleo-primer.git cleo-primer

We'll update it.

**Comment by jlpoolen** [comment]
Yes, I was looking at the URL you specified.  

I used the command in your comment and successfully cloned the repository.

Thank you.
