### ISSUE TITLE
Cleo Score -- Why is it needed ?

### ISSUE THREAD

**Issue by Vadi** [LinkedInAttic/cleo#11]
Can someone shed some light on where to find details about Score being set along with Element and how to define a scoring strategy. Also is this is used for sorting the results inside Cleo.

**Comment by paulhoule** [comment]
If you have one million or so elements you will find that you need to have a subjective importance score to get good relevance.  If you sorted the hits by alphabetic order,  for instance,  people would be overwhelmed by things they don't know or care about and your typeahead would be useless.  (It might please your boss but it won't please the end users)

The scoring will depend on your application but generally you want the score to be proportional to an estimator of the probability that the user is thinking of a certain element.  In many ways this score is like the "PageRank" score that Google uses to rank web pages.

In the case of topics from Wikipedia,  for instance,  you get pretty satisfying results if you sort by the number of Wikipedia pages that link to your topic.  An alternate scoring system I am working on would use Wikipedia usage data and sort topics by how many visits each page gets.  It can get fancier than that too.

For the case of a business system,  let's say a CRM system,  you might make the score proportional to the annual revenue expected from the client,  or how many sales calls have been made to the client,  or how many times salespeople have looked at the record.

It is very simple to come up with a scoring strategy that is "pretty good",  but a lot of evaluation work would go into making a "great" scoring function and there isn't as much precedent for relevance in typeahead search as there is in conventional fulltext search.

**Comment by Vadi** [comment]
Thanks, that clarifies.
